name: Code Coverage

on:
  push:
    branches:
      - master

jobs:
  code-coverage:
    name: Code Coverage and Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests and collect coverage
        run: |
          coverage run --source=calculator -m unittest discover
          coverage xml -o coverage.xml
          coverage report

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          languages: python

      - name: Convert to SARIF format
        run: coverage json -o coverage.sarif

      - name: Upload SARIF report to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: coverage.sarif
